void _puts_recursion(char *s);
int _putchar(char ch);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int power_by(int, int);
int is_prime_number(int n);
int is_prime(int x, int y);
int is_palindrome(char *s);
int is_pali(char *s, char *f, char *l, int len);
int _strlen(char *s);
